
package com.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWsImpl", targetNamespace = "http://service.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWsImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getValue", targetNamespace = "http://service.com/", className = "com.service.GetValue")
    @ResponseWrapper(localName = "getValueResponse", targetNamespace = "http://service.com/", className = "com.service.GetValueResponse")
    @Action(input = "http://service.com/HelloWsImpl/getValueRequest", output = "http://service.com/HelloWsImpl/getValueResponse")
    public String getValue(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
